# Generated by Django 5.2.6 on 2025-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('numero_train', models.IntegerField(max_length=50)),
                ('date_reservation', models.DateTimeField()),
                ('nombre_personnes', models.IntegerField()),
            ],
        ),
    ]
